-- Migración: agregar columna pseudonymized_at_utc a cookie_consents
--
-- Bloque: bloque-cookie-consent-banner-v1 — Decisión D-08 (Capa 0).
-- Cristian aprobó 12 meses como plazo de pseudonimización (D-07).
--
-- La columna registra cuándo el job de pseudonimización nullificó
-- client_ip y user_agent de la fila. NULL = aún no pseudonimizada.
--
-- Referencias legales:
-- - GDPR Art. 5(1)(e): limitación del plazo de conservación de datos
--   personales ("limitación del plazo de conservación").
-- - Ley 21.719 Art. 14 — vigente 2026-12-01 según Diario Oficial
--   CVE 2583630, Art. 1° transitorio (día primero del mes vigésimo
--   cuarto posterior a la publicación 2024-12-13).
-- - URL fuente: https://www.bcn.cl/leychile/navegar?idNorma=1212270
-- - Fecha de verificación: 2026-04-21. Verificador: backend-builder (Tori).
--
-- Idempotente: ALTER TABLE ... ADD COLUMN falla con error si la columna
-- ya existe en PostgreSQL. Para producción ejecutar con lógica condicional
-- o verificar manualmente antes. En SQLite se puede envolver en un bloque
-- BEGIN/ROLLBACK. Recomendación: aplicar una sola vez y marcar como migrada.
--
-- IMPORTANTE: esta migración aplica sobre tablas EXISTENTES (no usa
-- IF NOT EXISTS en el ADD COLUMN — no soportado en PostgreSQL). Verificar
-- antes de ejecutar que la columna no exista.
--
-- Aplicación humana requerida: NO ejecutar en producción sin revisión.
-- El backend-builder no aplica migraciones a staging ni producción.

ALTER TABLE cookie_consents
    ADD COLUMN pseudonymized_at_utc TIMESTAMP NULL;
